mysql:
  dsn: root:xu20010502@tcp(47.115.224.241:3306)/fantasytime?charset=utf8mb4&parseTime=True&loc=Local
redis:
  addr: "47.115.224.241:6379"
  password: "xu20010502"
  DB: 0
  poolSize: 30
  minIdleConn: 30

timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H

port:
  server: 8883
  udp: 3001
  IP: 47.115.224.241
#  IP: 127.0.0.1
nacos:
  Ip: 47.115.224.241
  Port: 8848