info:
  contact: {}
paths:
  /AddFriend:
    put:
      consumes:
      - application/json
      description: 添加好友
      parameters:
      - description: userId
        in: query
        name: userId
        type: string
      - description: targetId
        in: query
        name: targetId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 添加好友
      tags:
      - User
  /GetContactStates:
    get:
      consumes:
      - application/json
      description: 可按社区按时间或分数排序查询帖子列表接口
      parameters:
      - description: ids
        in: query
        name: ids
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试查询用户好友的状态
      tags:
      - User
swagger: "2.0"
