info:
  contact: {}
paths:
  /GetContactStates:
    get:
      consumes:
      - application/json
      description: 可按社区按时间或分数排序查询帖子列表接口
      parameters:
      - description: ids
        in: query
        name: ids
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试查询用户好友的状态
      tags:
      - 帖子相关接口
swagger: "2.0"
